logging:
  level:
    ROOT: INFO
    springframework:
      web: INFO
server:
  port: ${SERVER_PORT:8080}
spring:
  output:
    ansi:
      enabled: ALWAYS
  rabbitmq:
    host: ${RABBIT_HOST:127.0.0.1}
    password: ${RABBIT_PASSWORD:guest}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:guest}
